import { createClient } from 'npm:@supabase/supabase-js@2.106.2'

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const allowedOrigins=()=>new Set([Deno.env.get('STAYQR_APP_URL'),Deno.env.get('STAYQR_APP_URLS')].filter(Boolean).flatMap((v)=>String(v).split(',')).map((v)=>v.trim().replace(/\/$/,'')).filter(Boolean))
function cors(req:Request){const o=req.headers.get('Origin')||'';const a=allowedOrigins();return{'Access-Control-Allow-Origin':a.has(o)?o:[...a][0]||o||'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Max-Age':'86400',Vary:'Origin'}}
function json(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json','Cache-Control':'no-store'}})}
function uuid(v:unknown,n:string){const x=String(v||'').trim();if(!UUID.test(x))throw new Error(`${n} must be a valid UUID.`);return x}
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map((x)=>x.toString(16).padStart(2,'0')).join('')}

Deno.serve(async(request)=>{
  if(request.method==='OPTIONS')return new Response('ok',{headers:cors(request)});if(request.method!=='POST')return json(request,405,{ok:false,error:'Method not allowed.'})
  try{
    const url=Deno.env.get('SUPABASE_URL');const anon=Deno.env.get('SUPABASE_ANON_KEY');const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anon||!service)throw new Error('Supabase function environment is incomplete.')
    const token=(request.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)return json(request,401,{ok:false,error:'Authentication is required.'})
    const auth=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
    const {data:{user},error:userError}=await auth.auth.getUser(token);if(userError||!user)return json(request,401,{ok:false,error:'Your StayQR session is invalid or expired.'})
    const body=await request.json().catch(()=>({}));const hotelId=uuid(body.hotel_id,'hotel_id');const guestId=uuid(body.guest_id,'guest_id');const guestSessionId=body.guest_session_id?uuid(body.guest_session_id,'guest_session_id'):null;const requestId=body.request_id?uuid(body.request_id,'request_id'):null
    const {data:permissions,error:permissionError}=await auth.rpc('get_my_hotel_permissions',{target_hotel_id:hotelId});if(permissionError)throw permissionError;if(!(permissions||[]).some((row:{permission_key?:string})=>row.permission_key==='guests.manage'))throw new Error('Aadhaar authentication access denied.')
    const {data:consent,error:consentError}=await admin.from('guest_consents').select('id').eq('hotel_id',hotelId).eq('guest_id',guestId).eq('purpose','aadhaar_online_authentication').eq('status','granted').is('revoked_at',null).order('captured_at',{ascending:false}).limit(1).maybeSingle();if(consentError)throw consentError;if(!consent)throw new Error('Record Aadhaar online authentication consent before authenticating.')
    const {data:readiness,error:readinessError}=await admin.from('platform_provider_readiness').select('status,environment,external_reference').eq('provider_key','uidai_online').single();if(readinessError)throw readinessError
    const enabled=(Deno.env.get('UIDAI_ONLINE_AUTH_ENABLED')||'').toLowerCase()==='true';const provider=(Deno.env.get('UIDAI_AUTH_PROVIDER')||'').trim();const providerUrl=(Deno.env.get('UIDAI_AUTH_PROVIDER_URL')||'').trim();const providerToken=(Deno.env.get('UIDAI_AUTH_PROVIDER_TOKEN')||'').trim();const hashPepper=(Deno.env.get('UIDAI_HASH_PEPPER')||'').trim()
    if(readiness.status!=='active'||!enabled||!provider||!providerUrl||!providerToken||hashPepper.length<32)return json(request,409,{ok:false,code:'provider_activation_pending',error:'Formal UIDAI online authentication is not active yet. Use the verified offline fallback until an authorized provider is configured.'})
    let row:Record<string,unknown>|null=null;let aadhaar='';let aadhaarHash='';let transactionReference='';let endpointAction='request_otp'
    if(requestId){const {data,error}=await admin.from('uidai_online_auth_requests').select('*').eq('id',requestId).eq('hotel_id',hotelId).eq('guest_id',guestId).single();if(error||!data)throw new Error('UIDAI authentication request was not found.');row=data;aadhaarHash=String(data.aadhaar_sha256);transactionReference=String(data.transaction_reference);endpointAction='verify_otp'}else{aadhaar=String(body.aadhaar_number||'').replace(/\D/g,'');if(!/^\d{12}$/.test(aadhaar))throw new Error('A valid 12-digit Aadhaar number is required.');aadhaarHash=await sha256(`${hotelId}:${aadhaar}:${hashPepper}`);transactionReference=`stayqr_uidai_${crypto.randomUUID()}`;const {data,error}=await admin.from('uidai_online_auth_requests').insert({hotel_id:hotelId,guest_id:guestId,guest_session_id:guestSessionId,consent_id:consent.id,actor_user_id:user.id,provider,transaction_reference:transactionReference,auth_mode:'otp',status:'created',aadhaar_last4:aadhaar.slice(-4),aadhaar_sha256:aadhaarHash,evidence:{provider_environment:readiness.environment,authorized_route_reference:readiness.external_reference||null}}).select('*').single();if(error)throw error;row=data}
    const otp=String(body.otp||'').replace(/\D/g,'');if(endpointAction==='verify_otp'&&!/^\d{4,8}$/.test(otp))throw new Error('A valid OTP is required.')
    const providerPayload=endpointAction==='request_otp'?{action:'request_otp',transaction_reference:transactionReference,aadhaar_number:aadhaar,consent:true,purpose:'hotel_guest_identity_verification'}:{action:'verify_otp',transaction_reference:transactionReference,provider_request_id:row?.provider_request_id,otp}
    const providerResponse=await fetch(providerUrl,{method:'POST',headers:{Authorization:`Bearer ${providerToken}`,'Content-Type':'application/json','X-StayQR-Provider':provider},body:JSON.stringify(providerPayload)});const providerBody=await providerResponse.json().catch(()=>({})) as Record<string,unknown>
    if(!providerResponse.ok)throw Object.assign(new Error(String(providerBody.message||providerBody.error||`Authorized UIDAI provider returned HTTP ${providerResponse.status}.`)),{providerCode:String(providerBody.code||providerResponse.status)})
    const rawStatus=String(providerBody.status||'pending').toLowerCase();const status=['verified','success','authenticated'].includes(rawStatus)?'verified':['otp_sent','pending_otp'].includes(rawStatus)?'otp_sent':['failed','rejected'].includes(rawStatus)?'failed':'pending';const providerRequestId=String(providerBody.request_id||providerBody.transaction_id||row?.provider_request_id||'')||null
    await admin.from('uidai_online_auth_requests').update({provider_request_id:providerRequestId,status,provider_response_code:String(providerBody.code||rawStatus).slice(0,120),failure_message:status==='failed'?String(providerBody.message||'Provider rejected authentication.').slice(0,500):null,responded_at:new Date().toISOString(),evidence:{provider,provider_status:rawStatus,transaction_reference:transactionReference,no_pid_retained:true}}).eq('id',row?.id)
    if(status==='verified')await admin.from('guest_identity_verifications').upsert({hotel_id:hotelId,guest_id:guestId,guest_session_id:guestSessionId,verification_method:'aadhaar_online_auth',provider,status:'verified',reference_id_masked:`****${String(row?.aadhaar_last4||aadhaar.slice(-4))}`,signature_valid:true,payload_sha256:aadhaarHash,verified_fields:{online_authentication:true,auth_mode:'otp'},source_version:'commercial-ready-rev1',verified_by:user.id,metadata:{uidai_online_request_id:row?.id,transaction_reference:transactionReference,no_aadhaar_or_otp_retained:true}},{onConflict:'hotel_id,guest_id,payload_sha256'})
    return json(request,200,{ok:true,request_id:row?.id,status,reference_id_masked:`****${String(row?.aadhaar_last4||aadhaar.slice(-4))}`})
  }catch(error){return json(request,400,{ok:false,error:error instanceof Error?error.message:'UIDAI online authentication failed.',code:String((error as Record<string,unknown>)?.providerCode||'uidai_online_error')})}
})
