import { createClient } from 'npm:@supabase/supabase-js@2.106.2'

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const PROVIDER=/^[a-z0-9][a-z0-9._-]{1,79}$/i
const VERIFYABLE=new Set(['otp_sent','pending'])
const TERMINAL=new Set(['verified','failed','expired','cancelled'])
const OTP_TTL_MS=10*60*1000
const allowedOrigins=()=>new Set([Deno.env.get('STAYQR_APP_URL'),Deno.env.get('STAYQR_APP_URLS')].filter(Boolean).flatMap((v)=>String(v).split(',')).map((v)=>v.trim().replace(/\/$/,'')).filter(Boolean))
function cors(req:Request){const o=req.headers.get('Origin')||'';const a=allowedOrigins();return{'Access-Control-Allow-Origin':a.has(o)?o:[...a][0]||o||'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Max-Age':'86400',Vary:'Origin'}}
function json(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json','Cache-Control':'no-store'}})}
function uuid(v:unknown,n:string){const x=String(v||'').trim();if(!UUID.test(x))throw Object.assign(new Error(`${n} must be a valid UUID.`),{safeCode:'invalid_request'});return x}
function safeError(code='uidai_online_error'){const map:Record<string,string>={invalid_request:'The UIDAI authentication request is invalid.',request_not_found:'UIDAI authentication request was not found.',request_expired:'The UIDAI authentication request has expired. Request a new OTP.',request_complete:'This UIDAI authentication request is already complete.',request_busy:'This UIDAI authentication request is already being processed.',attempt_limit:'The maximum OTP verification attempts have been reached. Request a new OTP.',stay_binding_mismatch:'The authentication request does not match the original guest stay.',provider_protocol_error:'The authorized UIDAI provider returned an invalid response.',provider_rejected:'The authorized UIDAI provider rejected the authentication request.',persistence_error:'UIDAI authentication evidence could not be safely persisted. No verification was recorded.'};return map[code]||'UIDAI online authentication failed.'}
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map((x)=>x.toString(16).padStart(2,'0')).join('')}
function providerEndpoint(value:string){let u:URL;try{u=new URL(value)}catch{throw Object.assign(new Error('invalid provider URL'),{safeCode:'provider_activation_pending'})}if(u.protocol!=='https:'||u.username||u.password)throw Object.assign(new Error('invalid provider URL'),{safeCode:'provider_activation_pending'});return value}
function mapProviderStatus(action:'request_otp'|'verify_otp',body:Record<string,unknown>){const raw=String(body.status||'').trim().toLowerCase();if(action==='request_otp'){if(['otp_sent','pending_otp'].includes(raw))return{raw,status:'otp_sent'};if(raw==='pending')return{raw,status:'pending'};if(['failed','rejected'].includes(raw))return{raw,status:'failed'};throw Object.assign(new Error('unexpected provider response'),{safeCode:'provider_protocol_error'})}if(['verified','success','authenticated'].includes(raw))return{raw,status:'verified'};if(['failed','rejected','invalid_otp'].includes(raw))return{raw,status:'failed'};if(['pending','processing'].includes(raw))return{raw,status:'pending'};throw Object.assign(new Error('unexpected provider response'),{safeCode:'provider_protocol_error'})}
function providerRequestId(body:Record<string,unknown>,fallback:unknown=null){const value=String(body.request_id||body.transaction_id||fallback||'').trim();return value?value.slice(0,240):null}

Deno.serve(async(request)=>{
  if(request.method==='OPTIONS')return new Response('ok',{headers:cors(request)});if(request.method!=='POST')return json(request,405,{ok:false,error:'Method not allowed.'})
  try{
    const url=Deno.env.get('SUPABASE_URL');const anon=Deno.env.get('SUPABASE_ANON_KEY');const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anon||!service)throw Object.assign(new Error('environment incomplete'),{safeCode:'provider_activation_pending'})
    const token=(request.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)return json(request,401,{ok:false,error:'Authentication is required.'})
    const auth=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
    const {data:{user},error:userError}=await auth.auth.getUser(token);if(userError||!user)return json(request,401,{ok:false,error:'Your StayQR session is invalid or expired.'})
    const body=await request.json().catch(()=>({}));const hotelId=uuid(body.hotel_id,'hotel_id');const guestId=uuid(body.guest_id,'guest_id');const suppliedGuestSessionId=body.guest_session_id?uuid(body.guest_session_id,'guest_session_id'):null;const requestId=body.request_id?uuid(body.request_id,'request_id'):null
    const {data:permissions,error:permissionError}=await auth.rpc('get_my_hotel_permissions',{target_hotel_id:hotelId});if(permissionError)throw permissionError;if(!(permissions||[]).some((row:{permission_key?:string})=>row.permission_key==='guests.manage'))return json(request,403,{ok:false,error:'Aadhaar authentication access denied.'})
    const {data:consent,error:consentError}=await admin.from('guest_consents').select('id').eq('hotel_id',hotelId).eq('guest_id',guestId).eq('purpose','aadhaar_online_authentication').eq('status','granted').is('revoked_at',null).order('captured_at',{ascending:false}).limit(1).maybeSingle();if(consentError)throw consentError;if(!consent)return json(request,409,{ok:false,code:'consent_required',error:'Record Aadhaar online authentication consent before authenticating.'})
    const {data:readiness,error:readinessError}=await admin.from('platform_provider_readiness').select('status,environment,external_reference').eq('provider_key','uidai_online').single();if(readinessError)throw readinessError
    const enabled=(Deno.env.get('UIDAI_ONLINE_AUTH_ENABLED')||'').toLowerCase()==='true';const provider=(Deno.env.get('UIDAI_AUTH_PROVIDER')||'').trim();const providerUrlRaw=(Deno.env.get('UIDAI_AUTH_PROVIDER_URL')||'').trim();const providerToken=(Deno.env.get('UIDAI_AUTH_PROVIDER_TOKEN')||'').trim();const hashPepper=(Deno.env.get('UIDAI_HASH_PEPPER')||'').trim()
    if(readiness.status!=='active'||!enabled||!PROVIDER.test(provider)||!providerUrlRaw||!providerToken||hashPepper.length<32)return json(request,409,{ok:false,code:'provider_activation_pending',error:'Formal UIDAI online authentication is not active yet. Use the verified offline fallback until an authorized provider is configured.'})
    const providerUrl=providerEndpoint(providerUrlRaw)

    let row:Record<string,unknown>;let aadhaar='';let aadhaarHash='';let transactionReference='';let action:'request_otp'|'verify_otp'=requestId?'verify_otp':'request_otp'
    if(requestId){
      const {data,error}=await admin.from('uidai_online_auth_requests').select('*').eq('id',requestId).eq('hotel_id',hotelId).eq('guest_id',guestId).single();if(error||!data)return json(request,404,{ok:false,code:'request_not_found',error:safeError('request_not_found')});row=data
      const storedSessionId=row.guest_session_id?String(row.guest_session_id):null;if(storedSessionId!==suppliedGuestSessionId)return json(request,409,{ok:false,code:'stay_binding_mismatch',error:safeError('stay_binding_mismatch')})
      const status=String(row.status||'');if(status==='evidence_pending'){
        const {error:evidenceError}=await admin.from('guest_identity_verifications').upsert({hotel_id:hotelId,guest_id:guestId,guest_session_id:storedSessionId,verification_method:'aadhaar_online_auth',provider:String(row.provider),status:'verified',reference_id_masked:`****${String(row.aadhaar_last4||'')}`,signature_valid:true,payload_sha256:String(row.aadhaar_sha256),verified_fields:{online_authentication:true,auth_mode:'otp'},source_version:'commercial-ready-rev1',verified_by:user.id,metadata:{uidai_online_request_id:row.id,transaction_reference:String(row.transaction_reference),no_aadhaar_or_otp_retained:true}},{onConflict:'hotel_id,guest_id,payload_sha256'});if(evidenceError)return json(request,503,{ok:false,code:'persistence_error',error:safeError('persistence_error')})
        const {error:finalizeError}=await admin.from('uidai_online_auth_requests').update({status:'verified',responded_at:new Date().toISOString()}).eq('id',row.id).eq('status','evidence_pending');if(finalizeError)return json(request,503,{ok:false,code:'persistence_error',error:safeError('persistence_error')});return json(request,200,{ok:true,request_id:row.id,status:'verified',reference_id_masked:`****${String(row.aadhaar_last4||'')}`})
      }
      if(TERMINAL.has(status))return json(request,409,{ok:false,code:'request_complete',error:safeError('request_complete')});if(status==='verifying')return json(request,409,{ok:false,code:'request_busy',error:safeError('request_busy')});if(!VERIFYABLE.has(status))return json(request,409,{ok:false,code:'request_complete',error:safeError('request_complete')})
      const expiresAt=new Date(String(row.expires_at||new Date(String(row.requested_at)).getTime()+OTP_TTL_MS));if(!Number.isFinite(expiresAt.getTime())||expiresAt.getTime()<=Date.now()){const {error:expireError}=await admin.from('uidai_online_auth_requests').update({status:'expired',responded_at:new Date().toISOString()}).eq('id',row.id).in('status',['otp_sent','pending']);if(expireError)throw expireError;return json(request,409,{ok:false,code:'request_expired',error:safeError('request_expired')})}
      const attempts=Number(row.verification_attempts||0);const maxAttempts=Number(row.max_verification_attempts||5);if(attempts>=maxAttempts)return json(request,429,{ok:false,code:'attempt_limit',error:safeError('attempt_limit')})
      const otp=String(body.otp||'').replace(/\D/g,'');if(!/^\d{4,8}$/.test(otp))return json(request,400,{ok:false,code:'invalid_request',error:'A valid OTP is required.'})
      const {data:claimed,error:claimError}=await admin.from('uidai_online_auth_requests').update({status:'verifying',verification_attempts:attempts+1}).eq('id',row.id).eq('verification_attempts',attempts).in('status',['otp_sent','pending']).select('*').maybeSingle();if(claimError)throw claimError;if(!claimed)return json(request,409,{ok:false,code:'request_busy',error:safeError('request_busy')});row=claimed;aadhaarHash=String(row.aadhaar_sha256);transactionReference=String(row.transaction_reference)
      const providerPayload={action:'verify_otp',transaction_reference:transactionReference,provider_request_id:row.provider_request_id,otp}
      let providerResponse:Response;try{providerResponse=await fetch(providerUrl,{method:'POST',headers:{Authorization:`Bearer ${providerToken}`,'Content-Type':'application/json','X-StayQR-Provider':provider},body:JSON.stringify(providerPayload)})}catch{await admin.from('uidai_online_auth_requests').update({status:'pending',failure_message:'Authorized provider could not be reached.',responded_at:new Date().toISOString()}).eq('id',row.id).eq('status','verifying');return json(request,502,{ok:false,code:'provider_unavailable',error:'The authorized UIDAI provider could not be reached. Try again safely.'})}
      const providerBody=await providerResponse.json().catch(()=>({})) as Record<string,unknown>;if(!providerResponse.ok){await admin.from('uidai_online_auth_requests').update({status:'pending',provider_response_code:String(providerBody.code||providerResponse.status).slice(0,120),failure_message:'Authorized provider rejected or could not process the OTP.',responded_at:new Date().toISOString()}).eq('id',row.id).eq('status','verifying');return json(request,400,{ok:false,code:'provider_rejected',error:safeError('provider_rejected')})}
      const mapped=mapProviderStatus(action,providerBody);const pReq=providerRequestId(providerBody,row.provider_request_id)
      if(mapped.status!=='verified'){const next=mapped.status==='failed'?'failed':'pending';const {error:updateError}=await admin.from('uidai_online_auth_requests').update({provider_request_id:pReq,status:next,provider_response_code:String(providerBody.code||mapped.raw).slice(0,120),failure_message:next==='failed'?'Authorized provider rejected authentication.':null,responded_at:new Date().toISOString(),evidence:{provider,provider_status:mapped.raw,transaction_reference:transactionReference,no_pid_retained:true}}).eq('id',row.id).eq('status','verifying');if(updateError)throw updateError;return json(request,200,{ok:true,request_id:row.id,status:next,reference_id_masked:`****${String(row.aadhaar_last4||'')}`})}
      const now=new Date().toISOString();const {error:markError}=await admin.from('uidai_online_auth_requests').update({provider_request_id:pReq,status:'evidence_pending',provider_response_code:String(providerBody.code||mapped.raw).slice(0,120),failure_message:null,provider_verified_at:now,responded_at:now,evidence:{provider,provider_status:mapped.raw,transaction_reference:transactionReference,no_pid_retained:true}}).eq('id',row.id).eq('status','verifying');if(markError)return json(request,503,{ok:false,code:'persistence_error',error:safeError('persistence_error')})
      const {error:evidenceError}=await admin.from('guest_identity_verifications').upsert({hotel_id:hotelId,guest_id:guestId,guest_session_id:storedSessionId,verification_method:'aadhaar_online_auth',provider,status:'verified',reference_id_masked:`****${String(row.aadhaar_last4||'')}`,signature_valid:true,payload_sha256:aadhaarHash,verified_fields:{online_authentication:true,auth_mode:'otp'},source_version:'commercial-ready-rev1',verified_by:user.id,metadata:{uidai_online_request_id:row.id,transaction_reference:transactionReference,no_aadhaar_or_otp_retained:true}},{onConflict:'hotel_id,guest_id,payload_sha256'});if(evidenceError)return json(request,503,{ok:false,code:'persistence_error',error:safeError('persistence_error')})
      const {error:finalizeError}=await admin.from('uidai_online_auth_requests').update({status:'verified',responded_at:new Date().toISOString()}).eq('id',row.id).eq('status','evidence_pending');if(finalizeError)return json(request,503,{ok:false,code:'persistence_error',error:safeError('persistence_error')})
      return json(request,200,{ok:true,request_id:row.id,status:'verified',reference_id_masked:`****${String(row.aadhaar_last4||'')}`})
    }

    aadhaar=String(body.aadhaar_number||'').replace(/\D/g,'');if(!/^\d{12}$/.test(aadhaar))return json(request,400,{ok:false,code:'invalid_request',error:'A valid 12-digit Aadhaar number is required.'});aadhaarHash=await sha256(`${hotelId}:${aadhaar}:${hashPepper}`);transactionReference=`stayqr_uidai_${crypto.randomUUID()}`;const expiresAt=new Date(Date.now()+OTP_TTL_MS).toISOString()
    const {data:created,error:createError}=await admin.from('uidai_online_auth_requests').insert({hotel_id:hotelId,guest_id:guestId,guest_session_id:suppliedGuestSessionId,consent_id:consent.id,actor_user_id:user.id,provider,transaction_reference:transactionReference,auth_mode:'otp',status:'created',aadhaar_last4:aadhaar.slice(-4),aadhaar_sha256:aadhaarHash,verification_attempts:0,max_verification_attempts:5,expires_at:expiresAt,evidence:{provider_environment:readiness.environment,authorized_route_reference:readiness.external_reference||null}}).select('*').single();if(createError||!created)return json(request,503,{ok:false,code:'persistence_error',error:safeError('persistence_error')});row=created
    const providerPayload={action:'request_otp',transaction_reference:transactionReference,aadhaar_number:aadhaar,consent:true,purpose:'hotel_guest_identity_verification'}
    let providerResponse:Response;try{providerResponse=await fetch(providerUrl,{method:'POST',headers:{Authorization:`Bearer ${providerToken}`,'Content-Type':'application/json','X-StayQR-Provider':provider},body:JSON.stringify(providerPayload)})}catch{await admin.from('uidai_online_auth_requests').update({status:'failed',failure_message:'Authorized provider could not be reached.',responded_at:new Date().toISOString()}).eq('id',row.id);return json(request,502,{ok:false,code:'provider_unavailable',error:'The authorized UIDAI provider could not be reached. Try again safely.'})}finally{aadhaar=''}
    const providerBody=await providerResponse.json().catch(()=>({})) as Record<string,unknown>;if(!providerResponse.ok){await admin.from('uidai_online_auth_requests').update({status:'failed',provider_response_code:String(providerBody.code||providerResponse.status).slice(0,120),failure_message:'Authorized provider rejected the OTP request.',responded_at:new Date().toISOString()}).eq('id',row.id);return json(request,400,{ok:false,code:'provider_rejected',error:safeError('provider_rejected')})}
    const mapped=mapProviderStatus(action,providerBody);const pReq=providerRequestId(providerBody);if(mapped.status==='otp_sent'&&!pReq){await admin.from('uidai_online_auth_requests').update({status:'failed',failure_message:'Authorized provider response did not include a request reference.',responded_at:new Date().toISOString()}).eq('id',row.id);return json(request,502,{ok:false,code:'provider_protocol_error',error:safeError('provider_protocol_error')})}
    const {error:updateError}=await admin.from('uidai_online_auth_requests').update({provider_request_id:pReq,status:mapped.status,provider_response_code:String(providerBody.code||mapped.raw).slice(0,120),failure_message:mapped.status==='failed'?'Authorized provider rejected authentication.':null,responded_at:new Date().toISOString(),evidence:{provider,provider_status:mapped.raw,transaction_reference:transactionReference,no_pid_retained:true}}).eq('id',row.id);if(updateError)return json(request,503,{ok:false,code:'persistence_error',error:safeError('persistence_error')})
    return json(request,200,{ok:true,request_id:row.id,status:mapped.status,reference_id_masked:`****${String(row.aadhaar_last4||'')}`})
  }catch(error){const code=String((error as Record<string,unknown>)?.safeCode||'uidai_online_error');console.error('UIDAI online auth failure',{code});return json(request,code==='provider_activation_pending'?409:400,{ok:false,error:safeError(code),code})}
})
