-- StayQR v1.0 — Audit 064 Day 14 Final Closure REV1
-- Run only after Migration 050, frontend REV5, browser review and Publish.
-- Expected: 48 rows, 48 passed, 0 failures.

with checks(test_name,passed,details) as (
 values
 ('01_settings',to_regclass('public.guest_guide_settings') is not null,'Settings table exists.'),
 ('02_sections',to_regclass('public.guest_guide_sections') is not null,'Sections table exists.'),
 ('03_items',to_regclass('public.guest_guide_items') is not null,'Items table exists.'),
 ('04_media',to_regclass('public.guest_guide_media') is not null,'Media table exists.'),
 ('05_payment',to_regclass('public.guest_guide_payment_profiles') is not null,'Payment table exists.'),
 ('06_greetings',to_regclass('public.guest_guide_greetings') is not null,'Greetings table exists.'),
 ('07_versions',to_regclass('public.guest_guide_versions') is not null,'Versions table exists.'),
 ('08_feedback',to_regclass('public.guest_feedback') is not null,'Feedback table exists.'),
 ('09_renderer_rev5',not exists(select 1 from public.guest_guide_settings where branding->>'renderer_version'<>'apex_signature_full_language_rev5'),'REV5 renderer configured.'),
 ('10_official_logo',not exists(select 1 from public.guest_guide_settings where branding->>'official_stayqr_logo'<>'/assets/stayqr-official-logo.png'),'Official logo configured.'),
 ('11_official_tagline',not exists(select 1 from public.guest_guide_settings where branding->>'stayqr_tagline'<>'Simplifying check-in'),'Official tagline configured.'),
 ('12_no_urdu',not exists(select 1 from public.guest_guide_settings where 'ur'=any(enabled_locales)),'Urdu excluded.'),
 ('13_default_enabled',not exists(select 1 from public.guest_guide_settings where not(default_locale=any(enabled_locales))),'Default locale enabled.'),
 ('14_all_published',not exists(select 1 from public.guest_guide_settings where publish_status<>'published'),'All guides published.'),
 ('15_version_reference',not exists(select 1 from public.guest_guide_settings s where not exists(select 1 from public.guest_guide_versions v where v.hotel_id=s.hotel_id and v.version_number=s.published_version)),'Published versions resolve.'),
 ('16_snapshot_renderer',not exists(select 1 from public.guest_guide_settings s join public.guest_guide_versions v on v.hotel_id=s.hotel_id and v.version_number=s.published_version where v.snapshot#>>'{settings,branding,renderer_version}'<>'apex_signature_full_language_rev5'),'Published snapshot contains REV5 marker.'),
 ('17_snapshot_logo',not exists(select 1 from public.guest_guide_settings s join public.guest_guide_versions v on v.hotel_id=s.hotel_id and v.version_number=s.published_version where v.snapshot#>>'{settings,branding,official_stayqr_logo}'<>'/assets/stayqr-official-logo.png'),'Published snapshot contains official logo.'),
 ('18_offer_object',not exists(select 1 from public.guest_guide_settings where jsonb_typeof(branding->'offer')<>'object'),'Offer configuration valid.'),
 ('19_hindi_ac',exists(select 1 from public.guest_guide_item_translations tr join public.guest_guide_items i on i.id=tr.item_id where i.item_key='air_conditioner' and tr.locale='hi' and jsonb_array_length(tr.instructions)>=5),'Hindi AC instructions complete.'),
 ('20_marathi_ac',exists(select 1 from public.guest_guide_item_translations tr join public.guest_guide_items i on i.id=tr.item_id where i.item_key='air_conditioner' and tr.locale='mr' and jsonb_array_length(tr.instructions)>=5),'Marathi AC instructions complete.'),
 ('21_tamil_ac',exists(select 1 from public.guest_guide_item_translations tr join public.guest_guide_items i on i.id=tr.item_id where i.item_key='air_conditioner' and tr.locale='ta' and jsonb_array_length(tr.instructions)>=5),'Tamil AC instructions complete.'),
 ('22_hindi_tv',exists(select 1 from public.guest_guide_item_translations tr join public.guest_guide_items i on i.id=tr.item_id where i.item_key='television_remote' and tr.locale='hi'),'Hindi TV translation exists.'),
 ('23_marathi_tv',exists(select 1 from public.guest_guide_item_translations tr join public.guest_guide_items i on i.id=tr.item_id where i.item_key='television_remote' and tr.locale='mr'),'Marathi TV translation exists.'),
 ('24_tamil_tv',exists(select 1 from public.guest_guide_item_translations tr join public.guest_guide_items i on i.id=tr.item_id where i.item_key='television_remote' and tr.locale='ta'),'Tamil TV translation exists.'),
 ('25_item_instruction_arrays',not exists(select 1 from public.guest_guide_item_translations where jsonb_typeof(instructions)<>'array'),'Instructions are arrays.'),
 ('26_guest_name_source',exists(select 1 from information_schema.columns where table_schema='public' and table_name='guests' and column_name='full_name'),'Guest name source exists.'),
 ('27_offer_section',exists(select 1 from public.guest_guide_sections where section_key='hero'),'Hero section exists.'),
 ('28_payment_qr_support',exists(select 1 from information_schema.columns where table_schema='public' and table_name='guest_guide_payment_profiles' and column_name='qr_media_id'),'Payment QR supported.'),
 ('29_upi_constraint_valid',exists(select 1 from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace where n.nspname='public' and t.relname='guest_guide_payment_profiles' and c.conname='guest_guide_payment_profiles_upi_check'),'UPI constraint exists.'),
 ('30_media_bucket',exists(select 1 from storage.buckets where id='guest-guide-media' and public),'Guest media bucket is available.'),
 ('31_device_media_categories',not exists(select 1 from public.guest_guide_media where category not in ('logo','profile','hero','property','room','bathroom','facility','dining','ac','ac_remote','tv','tv_remote','geyser','bathtub','safe','wifi','payment_qr','emergency','policy','custom')),'Media categories valid.'),
 ('32_media_paths',not exists(select 1 from public.guest_guide_media where split_part(object_path,'/',1)<>hotel_id::text),'Media paths tenant scoped.'),
 ('33_settings_rls',(select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='guest_guide_settings'),'Settings RLS enabled.'),
 ('34_items_rls',(select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='guest_guide_items'),'Items RLS enabled.'),
 ('35_media_rls',(select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='guest_guide_media'),'Media RLS enabled.'),
 ('36_anon_no_builder_write',not(has_table_privilege('anon','public.guest_guide_settings','INSERT') or has_table_privilege('anon','public.guest_guide_items','INSERT') or has_table_privilege('anon','public.guest_guide_media','INSERT')),'Anonymous builder writes blocked.'),
 ('37_premium_resolver',to_regprocedure('public.resolve_premium_guest_guide(text,text)') is not null,'Premium resolver exists.'),
 ('38_anon_resolver',has_function_privilege('anon','public.resolve_premium_guest_guide(text,text)','EXECUTE'),'Anonymous signed resolver access exists.'),
 ('39_auth_resolver',has_function_privilege('authenticated','public.resolve_premium_guest_guide(text,text)','EXECUTE'),'Authenticated signed resolver access exists.'),
 ('40_feedback_rpc',to_regprocedure('public.submit_guest_feedback(text,text,integer,text,boolean)') is not null,'Feedback RPC exists.'),
 ('41_review_rpc',to_regprocedure('public.record_guest_review_reward_action(text,text,text)') is not null,'Review RPC exists.'),
 ('42_no_expired_active',not exists(select 1 from public.guest_access_tokens where status='active' and expires_at<=now()),'No expired active token.'),
 ('43_one_active_token',not exists(select 1 from public.guest_access_tokens where status='active' group by guest_session_id having count(*)>1),'One active token per stay.'),
 ('44_revoked_evidence',exists(select 1 from public.guest_access_tokens where status='revoked'),'Rotation/revocation evidence exists.'),
 ('45_active_token',exists(select 1 from public.guest_access_tokens where status='active' and expires_at>now()),'At least one active test token exists.'),
 ('46_feedback_runtime',exists(select 1 from public.guest_feedback),'Private feedback runtime evidence exists.'),
 ('47_no_arbitrary_code',not exists(select 1 from information_schema.columns where table_schema='public' and table_name like 'guest_guide_%' and column_name in ('html','custom_html','javascript','custom_javascript','custom_css')),'No arbitrary code fields.'),
 ('48_token_helper',to_regprocedure('private.resolve_guest_access_token(text,text,boolean)') is not null,'Signed token helper retained.')
)
select test_name,passed,details from checks order by test_name;
