-- StayQR V1.1-C Audit 102 - consolidated structural/security acceptance
with checks(check_name,passed,details) as (
  values
  ('01_settings_table',to_regclass('public.whatsapp_channel_settings') is not null,'whatsapp_channel_settings'),
  ('02_health_table',to_regclass('public.whatsapp_delivery_health') is not null,'whatsapp_delivery_health'),
  ('03_settings_rls',(select relrowsecurity from pg_class where oid='public.whatsapp_channel_settings'::regclass),'RLS enabled'),
  ('04_health_rls',(select relrowsecurity from pg_class where oid='public.whatsapp_delivery_health'::regclass),'RLS enabled'),
  ('05_settings_select_policy',exists(select 1 from pg_policies where schemaname='public' and tablename='whatsapp_channel_settings' and policyname='whatsapp_channel_settings_select_v11c'),'policy'),
  ('06_health_select_policy',exists(select 1 from pg_policies where schemaname='public' and tablename='whatsapp_delivery_health' and policyname='whatsapp_delivery_health_select_v11c'),'policy'),
  ('07_settings_rpc',to_regprocedure('public.upsert_v11c_whatsapp_channel_settings(uuid,jsonb)') is not null,'RPC'),
  ('08_workspace_rpc',to_regprocedure('public.get_v11c_platform_workspace(uuid)') is not null,'RPC'),
  ('09_group_rpc',to_regprocedure('public.get_v11c_multi_property_overview()') is not null,'RPC'),
  ('10_support_touch_rpc',to_regprocedure('public.touch_v11c_support_access(uuid)') is not null,'RPC'),
  ('11_support_start_exists',to_regprocedure('public.start_safe_support_access(uuid,text,integer,text[])') is not null,'RPC'),
  ('12_support_single_index',to_regclass('public.uq_v11c_support_one_active_admin') is not null,'one active session/admin'),
  ('13_support_last_seen',exists(select 1 from information_schema.columns where table_schema='public' and table_name='support_access_sessions' and column_name='last_seen_at'),'column'),
  ('14_support_revoked_reason',exists(select 1 from information_schema.columns where table_schema='public' and table_name='support_access_sessions' and column_name='revoked_reason'),'column'),
  ('15_support_max_120',position('duration_minutes>120' in replace(pg_get_functiondef('public.start_safe_support_access(uuid,text,integer,text[])'::regprocedure),' ',''))>0,'max 120'),
  ('16_support_reason_min',position('length(trim(reason))<12' in replace(pg_get_functiondef('public.start_safe_support_access(uuid,text,integer,text[])'::regprocedure),' ',''))>0,'reason minimum'),
  ('17_support_global_active_guard',position('End the current audited support session' in pg_get_functiondef('public.start_safe_support_access(uuid,text,integer,text[])'::regprocedure))>0,'single active guard'),
  ('18_group_staff_scope',position('public.staff' in pg_get_functiondef('public.get_v11c_multi_property_overview()'::regprocedure))>0,'staff access'),
  ('19_group_membership_scope',position('public.hotel_users' in pg_get_functiondef('public.get_v11c_multi_property_overview()'::regprocedure))>0,'hotel_users access'),
  ('20_group_no_platform_override',position('is_platform_admin' in pg_get_functiondef('public.get_v11c_multi_property_overview()'::regprocedure))=0,'no all-hotel admin shortcut'),
  ('21_workspace_access_guard',position('user_has_hotel_access' in pg_get_functiondef('public.get_v11c_platform_workspace(uuid)'::regprocedure))>0,'tenant access guard'),
  ('22_settings_permission_guard',position('user_has_any_permission' in pg_get_functiondef('public.upsert_v11c_whatsapp_channel_settings(uuid,jsonb)'::regprocedure))>0,'permission guard'),
  ('23_settings_provider_gate',position('active hotel-owned Meta sender' in pg_get_functiondef('public.upsert_v11c_whatsapp_channel_settings(uuid,jsonb)'::regprocedure))>0,'provider gate'),
  ('24_settings_template_gate',position('provider-approved template' in pg_get_functiondef('public.upsert_v11c_whatsapp_channel_settings(uuid,jsonb)'::regprocedure))>0,'template gate'),
  ('25_marketing_requires_channel',exists(select 1 from pg_constraint where conname='whatsapp_channel_settings_marketing_v11c_check'),'constraint'),
  ('26_failure_threshold_constraint',exists(select 1 from pg_constraint where conname='whatsapp_channel_settings_failure_v11c_check'),'constraint'),
  ('27_cooldown_constraint',exists(select 1 from pg_constraint where conname='whatsapp_channel_settings_cooldown_v11c_check'),'constraint'),
  ('28_circuit_state_constraint',exists(select 1 from pg_constraint where conname='whatsapp_delivery_health_state_v11c_check'),'constraint'),
  ('29_existing_guest_consents',to_regclass('public.guest_consents') is not null,'reused'),
  ('30_existing_suppressions',to_regclass('public.guest_communication_suppressions') is not null,'reused'),
  ('31_existing_campaigns',to_regclass('public.guest_communication_campaigns') is not null,'reused'),
  ('32_existing_recipients',to_regclass('public.guest_communication_recipients') is not null,'reused'),
  ('33_existing_events',to_regclass('public.guest_communication_events') is not null,'reused'),
  ('34_existing_provider_profiles',to_regclass('public.hotel_whatsapp_provider_profiles') is not null,'reused'),
  ('35_existing_templates',to_regclass('public.whatsapp_templates') is not null,'reused'),
  ('36_existing_consent_rpc',to_regprocedure('public.set_guest_consent(uuid,uuid,text,boolean,text,jsonb)') is not null,'reused'),
  ('37_existing_campaign_rpc',to_regprocedure('public.create_guest_whatsapp_campaign(uuid,text,text,text,text,text,uuid[])') is not null,'reused'),
  ('38_existing_manual_contact_rpc',to_regprocedure('public.prepare_manual_whatsapp_contact(uuid,uuid,text)') is not null,'reused'),
  ('39_support_events',to_regclass('public.support_access_events') is not null,'reused'),
  ('40_support_session_rls',(select relrowsecurity from pg_class where oid='public.support_access_sessions'::regclass),'existing RLS'),
  ('41_no_duplicate_active_support',not exists(select 1 from public.support_access_sessions where status='active' group by platform_admin_user_id having count(*)>1),'single session invariant'),
  ('42_no_expired_active_support',not exists(select 1 from public.support_access_sessions where status='active' and expires_at<=now()),'expired sessions closed'),
  ('43_settings_auth_select',has_table_privilege('authenticated','public.whatsapp_channel_settings','SELECT'),'authenticated select'),
  ('44_health_auth_select',has_table_privilege('authenticated','public.whatsapp_delivery_health','SELECT'),'authenticated select'),
  ('45_settings_no_auth_insert',not has_table_privilege('authenticated','public.whatsapp_channel_settings','INSERT'),'RPC writes only'),
  ('46_health_no_auth_write',not has_table_privilege('authenticated','public.whatsapp_delivery_health','UPDATE'),'service role health writes'),
  ('47_settings_service_write',has_table_privilege('service_role','public.whatsapp_channel_settings','UPDATE'),'service write'),
  ('48_health_service_write',has_table_privilege('service_role','public.whatsapp_delivery_health','UPDATE'),'service write')
)
select row_number() over() seq,check_name,passed,details from checks;
