import { createClient } from 'npm:@supabase/supabase-js@2.106.2'

const encoder=new TextEncoder()
function cors(){return{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-webhook-signature, x-webhook-timestamp, x-cashfree-signature, x-cashfree-timestamp','Access-Control-Allow-Methods':'POST, OPTIONS'}}
function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(),'Content-Type':'application/json','Cache-Control':'no-store'}})}
function value(input:unknown){return String(input||'').trim()}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
async function hmac(secret:string,payload:string){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(payload)));return btoa(String.fromCharCode(...bytes))}

Deno.serve(async(request)=>{
  if(request.method==='OPTIONS')return new Response('ok',{headers:cors()});if(request.method!=='POST')return json(405,{ok:false,error:'Method not allowed.'})
  try{
    const url=Deno.env.get('SUPABASE_URL');const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');const secret=Deno.env.get('CASHFREE_CLIENT_SECRET');if(!url||!service||!secret)throw new Error('Cashfree subscription webhook environment is incomplete.')
    const raw=await request.text();const timestamp=request.headers.get('x-webhook-timestamp')||request.headers.get('x-cashfree-timestamp')||'';const signature=request.headers.get('x-webhook-signature')||request.headers.get('x-cashfree-signature')||''
    if(!timestamp||!signature)return json(401,{ok:false,error:'Cashfree webhook signature and timestamp are required.'});if(!safeEqual(await hmac(secret,`${timestamp}${raw}`),signature))return json(401,{ok:false,error:'Cashfree webhook signature is invalid.'})
    const payload=JSON.parse(raw) as Record<string,unknown>;const eventType=value(payload.type||payload.event_type||payload.event).toLowerCase();const data=(payload.data||payload) as Record<string,unknown>;const subscription=(data.subscription_details||data.subscription||data) as Record<string,unknown>;const payment=(data.payment_details||data.payment||{}) as Record<string,unknown>
    const providerSubscriptionId=value(subscription.subscription_id||data.subscription_id);if(!providerSubscriptionId)throw new Error('Cashfree subscription ID is missing.')
    const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data:local,error:localError}=await admin.from('hotel_subscriptions').select('*').eq('provider','cashfree').eq('provider_subscription_id',providerSubscriptionId).maybeSingle();if(localError)throw localError;if(!local)return json(202,{ok:true,ignored:true,reason:'subscription_not_mapped'})
    const providerEventId=value(payload.event_id||data.event_id||payment.cf_payment_id||`${eventType}:${providerSubscriptionId}:${timestamp}`);const paymentStatus=value(payment.payment_status||data.payment_status||subscription.subscription_status||data.status).toLowerCase();let autopayStatus=local.autopay_status;let subscriptionStatus=local.status;let chargeStatus=local.last_charge_status;let retryCount=Number(local.recurring_retry_count||0)
    if(eventType.includes('auth')&&['success','active','authenticated'].some((x)=>paymentStatus.includes(x)))autopayStatus='active'
    if(eventType.includes('subscription')&&paymentStatus.includes('cancel'))autopayStatus='cancelled'
    if(eventType.includes('subscription')&&paymentStatus.includes('pause'))autopayStatus='paused'
    if(eventType.includes('payment')||eventType.includes('charge')){
      if(['success','paid'].some((x)=>paymentStatus.includes(x))){chargeStatus='paid';retryCount=0;subscriptionStatus='active'}
      else if(['fail','declin'].some((x)=>paymentStatus.includes(x))){chargeStatus='failed';retryCount+=1;subscriptionStatus='past_due';autopayStatus='past_due'}
    }
    const attemptPayload={hotel_id:local.hotel_id,subscription_id:local.id,provider:'cashfree',provider_payment_id:value(payment.cf_payment_id||payment.payment_id)||null,provider_event_id:providerEventId,attempt_type:eventType.includes('auth')?'authorization':'charge',amount_minor:payment.payment_amount?Math.round(Number(payment.payment_amount)*100):local.amount_minor,currency_code:local.currency_code||'INR',status:['success','paid','active','authenticated'].some((x)=>paymentStatus.includes(x))?'succeeded':['fail','declin'].some((x)=>paymentStatus.includes(x))?'failed':'processing',failure_code:value(payment.failure_code||data.error_code)||null,failure_message:value(payment.failure_reason||data.error_message).slice(0,500)||null,completed_at:['success','paid','fail','declin'].some((x)=>paymentStatus.includes(x))?new Date().toISOString():null,metadata:{event_type:eventType,provider_status:paymentStatus}}
    const {data:existingAttempt,error:existingAttemptError}=await admin.from('subscription_recurring_attempts').select('id').eq('provider','cashfree').eq('provider_event_id',providerEventId).maybeSingle();if(existingAttemptError)throw existingAttemptError
    const attemptWrite=existingAttempt?admin.from('subscription_recurring_attempts').update(attemptPayload).eq('id',existingAttempt.id):admin.from('subscription_recurring_attempts').insert(attemptPayload);const {error:attemptError}=await attemptWrite;if(attemptError)throw attemptError
    await admin.from('hotel_subscriptions').update({status:subscriptionStatus,provider_status:paymentStatus||local.provider_status,autopay_status:autopayStatus,mandate_status:value(subscription.authorization_status||subscription.mandate_status)||local.mandate_status,next_charge_at:subscription.next_schedule_date||subscription.next_charge_at||local.next_charge_at,last_charge_status:chargeStatus,last_charge_at:eventType.includes('payment')||eventType.includes('charge')?new Date().toISOString():local.last_charge_at,recurring_retry_count:retryCount,recurring_failure_code:chargeStatus==='failed'?value(payment.failure_code||data.error_code)||'provider_failure':null,recurring_failure_message:chargeStatus==='failed'?value(payment.failure_reason||data.error_message).slice(0,500):null,provider_metadata:{...(local.provider_metadata||{}),cashfree_subscription_last_event:{event_id:providerEventId,event_type:eventType,status:paymentStatus,received_at:new Date().toISOString()}},updated_at:new Date().toISOString()}).eq('id',local.id)
    await admin.from('hotels').update({subscription_status:subscriptionStatus,updated_at:new Date().toISOString()}).eq('id',local.hotel_id)
    return json(200,{ok:true,event_id:providerEventId,status:paymentStatus})
  }catch(error){return json(400,{ok:false,error:error instanceof Error?error.message:'Cashfree subscription webhook failed.'})}
})
