import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import { getCurrentHotel } from "../../lib/currentHotel";

export default function Invoices() {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedInvoice, setSelectedInvoice] = useState(null);
  const [currentHotel, setCurrentHotel] = useState(null);

  useEffect(() => {
    initPage();
  }, []);

  async function initPage() {
    const hotel = await getCurrentHotel();

    if (!hotel) {
      alert("No hotel assigned");
      setLoading(false);
      return;
    }

    setCurrentHotel(hotel);
    fetchInvoices(hotel.id);
  }

  async function fetchInvoices(hotelId = currentHotel?.id) {
    if (!hotelId) return;

    setLoading(true);

    const { data, error } = await supabase
      .from("invoices")
      .select(`
        *,
        guests (
          full_name,
          phone
        ),
        rooms (
          room_number,
          room_type
        )
      `)
      .eq("hotel_id", hotelId)
      .order("created_at", { ascending: false });

    if (error) {
      alert(error.message);
      setLoading(false);
      return;
    }

    setInvoices(data || []);
    setLoading(false);
  }

  function printInvoice(invoice) {
    const printWindow = window.open("", "_blank");

    printWindow.document.write(`
      <html>
        <head>
          <title>${invoice.invoice_number}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; color: #111; }
            .invoice-box { max-width: 800px; margin: auto; border: 1px solid #ddd; padding: 30px; }
            h1 { margin-bottom: 5px; }
            .gold { color: #b9962d; }
            table { width: 100%; border-collapse: collapse; margin-top: 30px; }
            th, td { border-bottom: 1px solid #ddd; padding: 12px; text-align: left; }
            .total { font-size: 22px; font-weight: bold; text-align: right; margin-top: 30px; }
            .footer { margin-top: 40px; font-size: 12px; color: #777; }
          </style>
        </head>

        <body>
          <div class="invoice-box">
            <h1>${currentHotel?.hotel_name || "Hotel"}</h1>
            <p class="gold">Powered by StayQR</p>

            <h2>Invoice</h2>
            <p><strong>Invoice No:</strong> ${invoice.invoice_number}</p>
            <p><strong>Date:</strong> ${new Date(invoice.created_at).toLocaleString("en-IN")}</p>

            <hr />

            <p><strong>Guest:</strong> ${invoice.guests?.full_name || "-"}</p>
            <p><strong>Phone:</strong> ${invoice.guests?.phone || "-"}</p>
            <p><strong>Room:</strong> ${invoice.rooms?.room_number || "-"} ${invoice.rooms?.room_type || ""}</p>

            <table>
              <thead>
                <tr>
                  <th>Description</th>
                  <th>Amount</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td>Room Charges</td>
                  <td>₹${invoice.room_amount || 0}</td>
                </tr>
                <tr>
                  <td>Food Charges</td>
                  <td>₹${invoice.food_amount || 0}</td>
                </tr>
                <tr>
                  <td>Manual Charges</td>
                  <td>₹${invoice.manual_amount || 0}</td>
                </tr>
                <tr>
                  <td>Service Charges</td>
                  <td>₹${invoice.service_amount || 0}</td>
                </tr>
              </tbody>
            </table>

            <div class="total">
              Total: ₹${invoice.total_amount || 0}
            </div>

            <p><strong>Status:</strong> ${invoice.payment_status}</p>

            <div class="footer">
              Thank you for staying with us.<br />
              This invoice was generated by StayQR.
            </div>
          </div>

          <script>
            window.print();
          </script>
        </body>
      </html>
    `);

    printWindow.document.close();
  }

  if (loading) {
    return <div style={page}>Loading invoices...</div>;
  }

  return (
    <div style={page}>
      <div style={header}>
        <div>
          <h1 style={title}>Invoices</h1>
          <p style={hotelName}>{currentHotel?.hotel_name || "Hotel"}</p>
          <p style={subtitle}>View, print and manage hotel invoices.</p>
        </div>

        <button style={refreshBtn} onClick={() => fetchInvoices(currentHotel?.id)}>
          Refresh
        </button>
      </div>

      <div style={statsGrid}>
        <Card title="Total Invoices" value={invoices.length} />
        <Card
          title="Paid Invoices"
          value={invoices.filter((i) => i.payment_status === "paid").length}
        />
        <Card
          title="Pending Invoices"
          value={invoices.filter((i) => i.payment_status !== "paid").length}
        />
        <Card
          title="Invoice Revenue"
          value={`₹${invoices.reduce(
            (sum, i) => sum + Number(i.total_amount || 0),
            0
          )}`}
        />
      </div>

      <div style={tableCard}>
        {invoices.length === 0 ? (
          <p>No invoices found.</p>
        ) : (
          <table style={table}>
            <thead>
              <tr>
                <th style={th}>Invoice</th>
                <th style={th}>Guest</th>
                <th style={th}>Room</th>
                <th style={th}>Room Amount</th>
                <th style={th}>Food</th>
                <th style={th}>Manual</th>
                <th style={th}>Total</th>
                <th style={th}>Status</th>
                <th style={th}>Date</th>
                <th style={th}>Action</th>
              </tr>
            </thead>

            <tbody>
              {invoices.map((invoice) => (
                <tr key={invoice.id}>
                  <td style={td}>{invoice.invoice_number}</td>
                  <td style={td}>{invoice.guests?.full_name || "-"}</td>
                  <td style={td}>Room {invoice.rooms?.room_number || "-"}</td>
                  <td style={td}>₹{invoice.room_amount || 0}</td>
                  <td style={td}>₹{invoice.food_amount || 0}</td>
                  <td style={td}>₹{invoice.manual_amount || 0}</td>
                  <td style={td}>₹{invoice.total_amount || 0}</td>
                  <td style={td}>
                    <span style={badge(invoice.payment_status)}>
                      {invoice.payment_status}
                    </span>
                  </td>
                  <td style={td}>
                    {new Date(invoice.created_at).toLocaleString("en-IN")}
                  </td>
                  <td style={td}>
                    <button style={smallBtn} onClick={() => setSelectedInvoice(invoice)}>
                      View
                    </button>

                    <button style={smallBtn} onClick={() => printInvoice(invoice)}>
                      Print
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {selectedInvoice && (
        <div style={modalOverlay}>
          <div style={modal}>
            <h2 style={{ color: "#d4af37" }}>Invoice Details</h2>

            <p><strong>Invoice:</strong> {selectedInvoice.invoice_number}</p>
            <p><strong>Guest:</strong> {selectedInvoice.guests?.full_name || "-"}</p>
            <p><strong>Phone:</strong> {selectedInvoice.guests?.phone || "-"}</p>
            <p><strong>Room:</strong> {selectedInvoice.rooms?.room_number || "-"}</p>

            <hr style={{ borderColor: "#222" }} />

            <p><strong>Room Charges:</strong> ₹{selectedInvoice.room_amount || 0}</p>
            <p><strong>Food Charges:</strong> ₹{selectedInvoice.food_amount || 0}</p>
            <p><strong>Manual Charges:</strong> ₹{selectedInvoice.manual_amount || 0}</p>
            <p><strong>Service Charges:</strong> ₹{selectedInvoice.service_amount || 0}</p>

            <h3>Total: ₹{selectedInvoice.total_amount || 0}</h3>

            <button style={smallBtn} onClick={() => printInvoice(selectedInvoice)}>
              Print Invoice
            </button>

            <button style={closeBtn} onClick={() => setSelectedInvoice(null)}>
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function Card({ title, value }) {
  return (
    <div style={statCard}>
      <span style={statLabel}>{title}</span>
      <strong style={statValue}>{value}</strong>
    </div>
  );
}

const page = {
  padding: "32px",
  color: "#fff",
};

const hotelName = {
  color: "#d4af37",
  marginBottom: "6px",
};

const header = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: "25px",
};

const title = {
  fontSize: "42px",
  marginBottom: "6px",
};

const subtitle = {
  color: "#aaa",
};

const refreshBtn = {
  background: "#d4af37",
  color: "#000",
  border: "none",
  borderRadius: "10px",
  padding: "12px 18px",
  fontWeight: 800,
  cursor: "pointer",
};

const statsGrid = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))",
  gap: "18px",
  marginBottom: "25px",
};

const statCard = {
  background: "#0f0f0f",
  border: "1px solid #222",
  borderRadius: "16px",
  padding: "20px",
};

const statLabel = {
  display: "block",
  color: "#d4af37",
  fontSize: "13px",
  marginBottom: "10px",
};

const statValue = {
  fontSize: "28px",
};

const tableCard = {
  background: "#0f0f0f",
  border: "1px solid #222",
  borderRadius: "18px",
  overflowX: "auto",
  padding: "10px",
};

const table = {
  width: "100%",
  borderCollapse: "collapse",
  minWidth: "1250px",
};

const th = {
  padding: "16px",
  textAlign: "left",
  color: "#d4af37",
  borderBottom: "1px solid #222",
};

const td = {
  padding: "16px",
  borderBottom: "1px solid #1f1f1f",
  verticalAlign: "top",
};

const smallBtn = {
  background: "#d4af37",
  color: "#000",
  border: "none",
  borderRadius: "8px",
  padding: "8px 12px",
  marginRight: "8px",
  fontWeight: 700,
  cursor: "pointer",
};

const closeBtn = {
  background: "#222",
  color: "#fff",
  border: "1px solid #444",
  borderRadius: "8px",
  padding: "8px 12px",
  marginLeft: "8px",
  cursor: "pointer",
};

const badge = (status) => ({
  padding: "7px 12px",
  borderRadius: "999px",
  background:
    status === "paid"
      ? "rgba(46,204,113,.18)"
      : "rgba(255,170,0,.18)",
  color: status === "paid" ? "#2ecc71" : "#ffaa00",
  fontWeight: 700,
  textTransform: "capitalize",
});

const modalOverlay = {
  position: "fixed",
  inset: 0,
  background: "rgba(0,0,0,0.75)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  zIndex: 9999,
};

const modal = {
  background: "#0f0f0f",
  border: "1px solid #333",
  borderRadius: "18px",
  padding: "30px",
  width: "90%",
  maxWidth: "520px",
};